server:
  port: 8989
spring:
  redis:
    host: 172.18.100.100
    port: 6379
    password: Kfcs@1234
    database: 1
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8 #最大连接
        max-idle: 8  #最大空闲
        min-idle: 0 #最小空闲
        max-wait: 1000ms  #连接等待时间

